In [24]:
#to ignore warnings
import warnings
warnings.filterwarnings('ignore')

import numpy as np
import pandas as pd
bt1 = pd.read_csv('tweets_bitcoin_week_1_20_06_2022_19_30_48.csv')
bt1.head()

,Unnamed: 0,id,date,content,user_name,profile_verified_status,reply_count,retweet_count,likes_count,retweetedTweet,quotedTweet,hashtags,cashtags,place
0,0,1213971406628765697,2020-01-05 23:51:52+00:00,Side by side view of GOLD and BITCOIN\n\nThese...,RookieXBT,True,3,21,108,NaN,NaN,NaN,"['BTCUSD', 'BTC', 'XAU', 'XAUUSD']",NaN
1,1,1213968448566501378,2020-01-05 23:40:07+00:00,"Right now, 1 btc is worth roughly 40 hours of ...",marcelamdax,False,10,3,61,NaN,NaN,NaN,NaN,NaN
2,2,1213967489840730112,2020-01-05 23:36:18+00:00,"$gold testing major 0.618 from 2011 highs, if ...",SmartContracter,False,22,29,214,NaN,NaN,NaN,"['gold', 'btc', 'xau']",NaN
3,3,1213967406663647234,2020-01-05 23:35:58+00:00,Gold SPIKES To $1590 (Multi-Year Highs) &gt; h...,ShortSqueezed1,False,1,9,24,NaN,NaN,"['silver', 'Iran', 'gold', 'Kenya', 'US', 'new...",NaN,NaN
4,4,1213966899534413824,2020-01-05 23:33:57+00:00,PoS Bitcoin on Cosmos will dominate as the cur...,jaesustein,False,9,12,67,NaN,NaN,NaN,NaN,NaN

In [3]:
bt1.shape

(3699, 14)

In [4]:
bt1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3699 entries, 0 to 3698
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Unnamed: 0               3699 non-null   int64
 1   id                       3699 non-null   int64
 2   date                     3699 non-null   object
 3   content                  3699 non-null   object
 4   user_name                3699 non-null   object
 5   profile_verified_status  3699 non-null   bool
 6   reply_count              3699 non-null   int64
 7   retweet_count            3699 non-null   int64
 8   likes_count              3699 non-null   int64
 9   retweetedTweet           0 non-null      float64
 10  quotedTweet              426 non-null    object
 11  hashtags                 1577 non-null   object
 12  cashtags                 1122 non-null   object
 13  place                    49 non-null     object
dtypes: bool(1), float64(1), int64(5), object(7)
memory usage: 379.4+ KB

In [5]:
bt1.describe()

,Unnamed: 0,id,reply_count,retweet_count,likes_count,retweetedTweet
count,3699.000000,3.699000e+03,3699.000000,3699.000000,3699.000000,0.0
mean,1849.000000,1.214890e+18,16.532306,25.809949,127.636388,NaN
std,1067.953651,6.856052e+14,87.068089,171.498135,1885.865936,NaN
min,0.000000,1.213612e+18,0.000000,0.000000,11.000000,NaN
25%,924.500000,1.214321e+18,2.000000,3.000000,28.000000,NaN
50%,1849.000000,1.214866e+18,4.000000,7.000000,44.000000,NaN
75%,2773.500000,1.215439e+18,9.000000,17.000000,85.000000,NaN
max,3698.000000,1.216145e+18,3070.000000,8236.000000,113970.000000,NaN

In [6]:
bt1.columns

Index(['Unnamed: 0', 'id', 'date', 'content', 'user_name',
       'profile_verified_status', 'reply_count', 'retweet_count',
       'likes_count', 'retweetedTweet', 'quotedTweet', 'hashtags', 'cashtags',
       'place'],
      dtype='object')

In [7]:
bt1.nunique()

Unnamed: 0                 3699
id                         3699
date                       3679
content                    3697
user_name                  1568
profile_verified_status       2
reply_count                 171
retweet_count               211
likes_count                 429
retweetedTweet                0
quotedTweet                 360
hashtags                    949
cashtags                    360
place                        36
dtype: int64

In [8]:
bt1['user_name'].unique

<bound method Series.unique of 0             RookieXBT
1           marcelamdax
2       SmartContracter
3        ShortSqueezed1
4            jaesustein
             ...
3694     patrickluberus
3695         runolgarun
3696          BigChonis
3697     cryptorecruitr
3698      TreosOfficial
Name: user_name, Length: 3699, dtype: object>

In [9]:
bt1.isnull().sum()

Unnamed: 0                    0
id                            0
date                          0
content                       0
user_name                     0
profile_verified_status       0
reply_count                   0
retweet_count                 0
likes_count                   0
retweetedTweet             3699
quotedTweet                3273
hashtags                   2122
cashtags                   2577
place                      3650
dtype: int64

In [10]:
# !pip install dataprep
# from dataprep.eda import plot
# plot(bt1)

In [11]:
# from dataprep.eda import plot
# plot(bt1)

In [12]:
# from dataprep.eda import create_report
# report = create_report(bt1)

# report.show()

In [13]:
bt1
bt1['date']

bt1['Dates'] = pd.to_datetime(bt1['date']).dt.date
bt1['Time'] = pd.to_datetime(bt1['date']).dt.time
bt1['Dates']

0       2020-01-05
1       2020-01-05
2       2020-01-05
3       2020-01-05
4       2020-01-05
           ...
3694    2020-01-11
3695    2020-01-11
3696    2020-01-11
3697    2020-01-11
3698    2020-01-11
Name: Dates, Length: 3699, dtype: object

In [14]:
days = bt1['Dates'].unique()
print(days)
d1 = bt1[bt1['Dates']==days[0]]
#bt1.groupby(by = ['Dates'], axis = 0).sum()
#gb.head(5)
print(d1)

[datetime.date(2020, 1, 5) datetime.date(2020, 1, 6)
 datetime.date(2020, 1, 7) datetime.date(2020, 1, 8)
 datetime.date(2020, 1, 9) datetime.date(2020, 1, 10)
 datetime.date(2020, 1, 11)]
     Unnamed: 0                   id                       date  \
0             0  1213971406628765697  2020-01-05 23:51:52+00:00
1             1  1213968448566501378  2020-01-05 23:40:07+00:00
2             2  1213967489840730112  2020-01-05 23:36:18+00:00
3             3  1213967406663647234  2020-01-05 23:35:58+00:00
4             4  1213966899534413824  2020-01-05 23:33:57+00:00
..          ...                  ...                        ...
401         401  1213615043453038592  2020-01-05 00:15:48+00:00
402         402  1213613751364141057  2020-01-05 00:10:40+00:00
403         403  1213612997266083841  2020-01-05 00:07:41+00:00
404         404  1213612643166097409  2020-01-05 00:06:16+00:00
405         405  1213612233722388480  2020-01-05 00:04:39+00:00

                                               content        user_name  \
0    Side by side view of GOLD and BITCOIN\n\nThese...        RookieXBT
1    Right now, 1 btc is worth roughly 40 hours of ...      marcelamdax
2    $gold testing major 0.618 from 2011 highs, if ...  SmartContracter
3    Gold SPIKES To $1590 (Multi-Year Highs) &gt; h...   ShortSqueezed1
4    PoS Bitcoin on Cosmos will dominate as the cur...       jaesustein
..                                                 ...              ...
401  Bitcoin is a savings plan and a hedge against ...       ihatecodee
402  The hate against @nakamoto contributors for no...    iamDCinvestor
403  Important message ~ 5 months before the Bitcoi...       APompliano
404  Going all in on #IOTA felt nice today! Future ...       ThomasQvOG
405  $BTC\n\nOne or the other, i'm ready for both. ...          imBagsy

     profile_verified_status  reply_count  retweet_count  likes_count  \
0                       True            3             21          108
1                      False           10              3           61
2                      False           22             29          214
3                      False            1              9           24
4                      False            9             12           67
..                       ...          ...            ...          ...
401                    False            4              5           44
402                    False            9              3          126
403                     True          138            308         1549
404                    False           10             19          135
405                    False            2              1           23

     retweetedTweet quotedTweet  \
0               NaN         NaN
1               NaN         NaN
2               NaN         NaN
3               NaN         NaN
4               NaN         NaN
..              ...         ...
401             NaN         NaN
402             NaN         NaN
403             NaN         NaN
404             NaN         NaN
405             NaN         NaN

                                              hashtags  \
0                                                  NaN
1                                                  NaN
2                                                  NaN
3    ['silver', 'Iran', 'gold', 'Kenya', 'US', 'new...
4                                                  NaN
..                                                 ...
401                                                NaN
402                                                NaN
403                                                NaN
404                                ['IOTA', 'Bitcoin']
405                                                NaN

                               cashtags place       Dates      Time
0    ['BTCUSD', 'BTC', 'XAU', 'XAUUSD']   NaN  2020-01-05  23:51:52
1                                   NaN   NaN  2020-01-05  23:40:07
2                ['gold', 'btc', 'xau']   NaN  2020-01-05  23:36:18
3                                   NaN   NaN  2020-01-05  23:35:58
4                                   NaN   NaN  2020-01-05  23:33:57
..                                  ...   ...         ...       ...
401                                 NaN   NaN  2020-01-05  00:15:48
402                                 NaN   NaN  2020-01-05  00:10:40
403                                 NaN   NaN  2020-01-05  00:07:41
404                            ['IOTA']   NaN  2020-01-05  00:06:16
405                             ['BTC']   NaN  2020-01-05  00:04:39

[406 rows x 16 columns]

In [15]:
# d1g = d1.groupby('profile_verified_status')
# print(d1g)

# d1g = d1.groupby(['profile_verified_status'])
# d1g.describe()
# d1g.head()

d1g_sum = d1.groupby(['profile_verified_status']).sum()
d1g_sum

# d1g = d1.groupby(['profile_verified_status']).describe()
# print(d1g)

# df_eda["sex"].value_counts()
# heart_data.drop(['time'], axis=1, inplace = True)

,Unnamed: 0,id,reply_count,retweet_count,likes_count,retweetedTweet
profile_verified_status,,,,,,
False,70035.0,4.139096e+20,5178,6242,28906,0.0
True,12180.0,7.889848e+19,4337,3792,15903,0.0

In [16]:
d1g_count = d1.groupby(['profile_verified_status']).count()
d1g_count

,Unnamed: 0,id,date,content,user_name,reply_count,retweet_count,likes_count,retweetedTweet,quotedTweet,hashtags,cashtags,place,Dates,Time
profile_verified_status,,,,,,,,,,,,,,,
False,341,341,341,341,341,341,341,341,0,37,133,86,7,341,341
True,65,65,65,65,65,65,65,65,0,14,28,10,1,65,65

In [20]:
d1
user_counts = d1["user_name"].value_counts()
# print(d1["user_name"].value_counts())
# d1["user_name"].value_counts()
# d1["user_count"] = d1["user_name"].value_counts()


# print(d1.sort_values("user_name", inplace = True))

In [55]:
df_pfc = pd.DataFrame(user_counts)
df_pfc.head(15)

                 user_name
Bitsahara                5
cryptorecruitr           5
notgrubles               5
PeterMcCormack           4
theonevortex             4
HillebrandMax            4
Rhythmtrader             4
BitcoinErrorLog          4
BitcoinMemeHub           4
BitcoinIsSaving          4
MartyBent                3
imBagsy                  3
hodlonaut                3
_electronicCash          3
giveawayABC              3

In [53]:
lst = []
for item in user_counts.index:
    if user_counts[item] > 3:
        lst.append(item)
lst

['Bitsahara',
 'cryptorecruitr',
 'notgrubles',
 'PeterMcCormack',
 'theonevortex',
 'HillebrandMax',
 'Rhythmtrader',
 'BitcoinErrorLog',
 'BitcoinMemeHub',
 'BitcoinIsSaving']

In [58]:
d1['user_count'] = d1.groupby('user_name')['user_name'].transform('count')
#print(d1.sort_values(by=['user_name']).to_string())

In [59]:
d1.sort_values(by=['user_count'])
  
sub_d1 = d1[d1.groupby('user_name').user_name.transform('count')<=3].copy()
#print(sub_d1.to_string())
# print(sub_d1)
sub_d1.shape

# print(df.to_string())

(363, 17)

In [69]:
#d1.drop(index = np.where(d1['user_name']==lst[0]), axis = 0, inplace =True)
bot_twt = d1[d1['user_name'] == lst[2]]

In [70]:
bot_twt.index

Int64Index([74, 127, 328, 339, 390], dtype='int64')

In [71]:
d1.drop(index= bot_twt.index, axis = 0, inplace =True)

In [72]:
d1["user_name"].value_counts()

BitcoinErrorLog    4
Rhythmtrader       4
theonevortex       4
HillebrandMax      4
PeterMcCormack     4
                  ..
ph_lux             1
mr_kristof007      1
WomanBlockchain    1
THE_FREE_COIN      1
ThomasQvOG         1
Name: user_name, Length: 309, dtype: int64